investigate "Use C++20 standard for macro parsing"
commit 9a043c26868

with llvm21.1.8 at least the processor on encountering
"}}}}}}}}}}}}}}}}"
spews: e.g.
/tmp/tmpHS5F8B6Z-tmp.h:5:54: error: extraneous closing brace ('}')

but the output seems to be correct